nav7FSC/HospitalManagementApp

- .idea/misc.xml
- src/main/java/org/education/hospitalmanagementapp/services/AuthService.java
> Updated with the new server

- src/main/java/org/education/hospitalmanagementapp/User.java
Created a User class with member variables, constructors, getter and setter methods
> Created User Class

- src/main/java/org/education/hospitalmanagementapp/App.java
- src/main/java/org/education/hospitalmanagementapp/controllers/LoginViewController.java
- src/main/java/org/education/hospitalmanagementapp/services/AuthServiceClass.java
Login page textfields send data to database when login button is clicked
> Login page textfields send data to database when login button is clicked

- src/main/java/org/education/hospitalmanagementapp/App.java
- src/main/java/org/education/hospitalmanagementapp/controllers/LoginViewController.java
- src/main/java/org/education/hospitalmanagementapp/controllers/RegistrationController.java
Connected RegistrationController with backend and register button on login page will bring you to the registration page
> Ashraf branch

- src/main/java/org/education/hospitalmanagementapp/controllers/DashBoardController.java
- src/main/java/org/education/hospitalmanagementapp/controllers/MainMenuController.java
- src/main/resources/org.education.hospitalmanagementapp/HospitalDashBoard.fxml
- src/main/resources/org.education.hospitalmanagementapp/MainMenu.fxml
Created HospitalDashBoard.fxml 
Added go to main menu button functionality
> Created HospitalDashBoard.fxml and DashBoardController.java

- src/main/java/org/education/hospitalmanagementapp/controllers/AppointmentSchedulerController.java
- src/main/java/org/education/hospitalmanagementapp/controllers/MainMenuController.java
- src/main/resources/org.education.hospitalmanagementapp/MainMenu.fxml
- src/main/resources/org.education.hospitalmanagementapp/ScheduleAppointment.fxml
Added functionality to go from main menu to ScheduleAppointment.fxml
> Added functionality to go from main menu to ScheduleAppointment.fxml

- src/main/java/org/education/hospitalmanagementapp/services/AuthServiceClass.java
Removed unneeded methods from AuthServiceClass.java
> Removed unneeded methods from AuthServiceClass.java

- src/main/java/org/education/hospitalmanagementapp/controllers/DashBoardController.java
- src/main/java/org/education/hospitalmanagementapp/controllers/MainMenuController.java
- src/main/resources/org.education.hospitalmanagementapp/HospitalDashBoard.fxml
- src/main/resources/org.education.hospitalmanagementapp/MainMenu.fxml
Sign out buttons will return user to the login page
> Sign out buttons will return user to the login page

- src/main/java/org/education/hospitalmanagementapp/controllers/LoginViewController.java
- src/main/java/org/education/hospitalmanagementapp/controllers/RegistrationController.java
- src/main/java/org/education/hospitalmanagementapp/services/AuthServiceClass.java
Created method validateUser in AuthServiceClass to check if the user credentials are valid and already stored in the database
> Proper Login credentials needed to login

- src/main/java/org/education/hospitalmanagementapp/AlertMessages.java
- src/main/java/org/education/hospitalmanagementapp/controllers/LoginViewController.java
- src/main/java/org/education/hospitalmanagementapp/controllers/RegistrationController.java
- src/main/java/org/education/hospitalmanagementapp/services/AuthServiceClass.java
Created AlertMessages.java, added regex for sign up, user must sign in with proper credentials
> Created AlertMessages.java, added regex for sign up

- src/main/java/org/education/hospitalmanagementapp/AlertMessages.java
- src/main/java/org/education/hospitalmanagementapp/controllers/InventoryController.java
- src/main/java/org/education/hospitalmanagementapp/controllers/MainMenuController.java
- src/main/java/org/education/hospitalmanagementapp/controllers/UserManagementController.java
- src/main/java/org/education/hospitalmanagementapp/services/AuthServiceClass.java
- src/main/resources/org.education.hospitalmanagementapp/UserManagement.fxml
Added warningMessage() to AlertMessages, added update user info to AuthServiceClass, added code to UserManagementController so that user may now update their username and password.
> UserManagement page is now functional, able to make updates

- .idea/misc.xml
- src/main/java/org/education/hospitalmanagementapp/controllers/AppointmentSchedulerController.java
- src/main/java/org/education/hospitalmanagementapp/controllers/BillingAndInvoiceController.java
- src/main/java/org/education/hospitalmanagementapp/controllers/InventoryController.java
- src/main/java/org/education/hospitalmanagementapp/controllers/MainMenuController.java
- src/main/java/org/education/hospitalmanagementapp/controllers/PatientManagerController.java
- src/main/java/org/education/hospitalmanagementapp/controllers/ReportGeneratorController.java
- src/main/resources/org.education.hospitalmanagementapp/Billing_And_Invoices.fxml
- src/main/resources/org.education.hospitalmanagementapp/HospitalPatientManagement.fxml
- src/main/resources/org.education.hospitalmanagementapp/HospitalReportGenerator.fxml
- src/main/resources/org.education.hospitalmanagementapp/Hospital_Inventory.fxml
- src/main/resources/org.education.hospitalmanagementapp/MainMenu.fxml
- src/main/resources/org.education.hospitalmanagementapp/ScheduleAppointment.fxml
Updated on action events for all buttons in the MainMenuController.java, AppointmentSchedulerController.java, BillingAndInvoiceController.java, InventoryController.java, PatientManagerController.java, and ReportGeneratorController.java
> Updated on action events for all buttons - Nav Singh

- src/main/resources/org.education.hospitalmanagementapp/Billing_And_Invoices.fxml
- src/main/resources/org.education.hospitalmanagementapp/HospitalDashBoard.fxml
- src/main/resources/org.education.hospitalmanagementapp/HospitalPatientManagement.fxml
- src/main/resources/org.education.hospitalmanagementapp/HospitalReportGenerator.fxml
- src/main/resources/org.education.hospitalmanagementapp/Hospital_Inventory.fxml
- src/main/resources/org.education.hospitalmanagementapp/LoginView.fxml
- src/main/resources/org.education.hospitalmanagementapp/MainMenu.fxml
- src/main/resources/org.education.hospitalmanagementapp/RegistrationView.fxml
- src/main/resources/org.education.hospitalmanagementapp/ScheduleAppointment.fxml
- src/main/resources/org.education.hospitalmanagementapp/SplashScreen.fxml
- src/main/resources/org.education.hospitalmanagementapp/UserManagement.fxml
Updated all titles in the FXML files to 'Inter Semi Bold Italic' for a polished and cohesive design. Standardized all other font contents to 'Inter Semi Bold' or 'Inter Semi Bold Italic' for consistency across the application.
> Updated Titles and Standardized Fonts Across All FXML Files - Nav Singh

- src/main/resources/org.education.hospitalmanagementapp/Billing_And_Invoices.fxml
- src/main/resources/org.education.hospitalmanagementapp/HospitalPatientManagement.fxml
- src/main/resources/org.education.hospitalmanagementapp/HospitalReportGenerator.fxml
- src/main/resources/org.education.hospitalmanagementapp/RegistrationView.fxml
Updated orientation of text fields in the fxml files.
> Updated orientation of text fields in the fxml files. - Nav Singh

- .idea/misc.xml
- src/main/java/org/education/hospitalmanagementapp/controllers/LoginViewController.java
- src/main/java/org/education/hospitalmanagementapp/controllers/RegistrationController.java
- src/main/resources/org.education.hospitalmanagementapp/LoginView.fxml
- src/main/resources/org.education.hospitalmanagementapp/RegistrationView.fxml
Replaced TextField with PasswordField in both the login and registration FXML to ensure passwords are masked during input. This change enhances security and prevents sensitive data from being visible as users type.
> Replaced text fields with password fields in login and registration pages - Nav Singh

- src/main/java/org/education/hospitalmanagementapp/controllers/PatientManagerController.java
- src/main/java/org/education/hospitalmanagementapp/services/AuthServiceClass.java
Created methods to update patient's number and address
Able to update patient's number and address now
> Created methods to update patient's number and address

- src/main/java/module-info.java
- src/main/java/org/education/hospitalmanagementapp/controllers/UserManagementController.java
- src/main/resources/org.education.hospitalmanagementapp/UserManagement.fxml
Converted the current password field from TextField to PasswordField to mask user input and enhance security. Added regex validation to both username and password fields to enforce input constraints. Applied these changes to the UserManagementController and updated the corresponding FXML file.
> Update Fields with Regex Validation - Change to PasswordField for Secure Input - Nav Singh

- .idea/misc.xml
- src/main/java/org/education/hospitalmanagementapp/AlertMessages.java
- src/main/java/org/education/hospitalmanagementapp/App.java
- src/main/java/org/education/hospitalmanagementapp/User.java
- src/main/java/org/education/hospitalmanagementapp/controllers/AppointmentSchedulerController.java
- src/main/java/org/education/hospitalmanagementapp/controllers/BillingAndInvoiceController.java
- src/main/java/org/education/hospitalmanagementapp/controllers/DashBoardController.java
- src/main/java/org/education/hospitalmanagementapp/controllers/LoginViewController.java
- src/main/java/org/education/hospitalmanagementapp/controllers/MainMenuController.java
- src/main/java/org/education/hospitalmanagementapp/controllers/PatientManagerController.java
- src/main/java/org/education/hospitalmanagementapp/controllers/RegistrationController.java
- src/main/java/org/education/hospitalmanagementapp/controllers/ReportGeneratorController.java
- src/main/java/org/education/hospitalmanagementapp/services/AuthServiceClass.java
Added Javadoc comments to all controller classes to improve code clarity and maintainability. These comments document the purpose, parameters, and expected behavior of each method.
> Added Javadoc comments to all controller classes - Nav Singh

- src/main/java/org/education/hospitalmanagementapp/controllers/AppointmentSchedulerController.java
- src/main/java/org/education/hospitalmanagementapp/controllers/MainMenuController.java
- src/main/java/org/education/hospitalmanagementapp/controllers/ReportGeneratorController.java
- src/main/resources/org.education.hospitalmanagementapp/HospitalReportGenerator.fxml
- src/main/resources/org.education.hospitalmanagementapp/LoginView.fxml
- src/main/resources/org.education.hospitalmanagementapp/MainMenu.fxml
- src/main/resources/org.education.hospitalmanagementapp/RegistrationView.fxml
- src/main/resources/org.education.hospitalmanagementapp/ScheduleAppointment.fxml
Removed unused and unnecessary notification badge elements from several FXML files and their corresponding controller classes. This change simplifies the UI and improves code maintainability.
> Removed Unused Notification Badge from FXML Files and Controllers - Nav Singh

- src/main/java/org/education/hospitalmanagementapp/controllers/PatientManagerController.java
- src/main/java/org/education/hospitalmanagementapp/services/AuthServiceClass.java
Added regex validation to all relevant fields: firstNameField, lastNameField, dobField, phoneNumberField, addressField, confirmFirstNameField, confirmLastNameField, changePhoneNumberField, changeAddressField. 
Input fields now turn red on invalid input and green when valid, with live-time updates as the user types. 
Implemented regex checks to validate formats for names, phone numbers, dates of birth, and addresses. 
Enhanced user experience by providing real-time visual feedback for invalid/valid inputs.
> Added regex validation with live feedback for all input fields in PatientManagerController.java - Nav Singh

- src/main/java/org/education/hospitalmanagementapp/controllers/RegistrationController.java
- src/main/resources/org.education.hospitalmanagementapp/RegistrationView.fxml
Implemented real-time input validation for text and password fields using regex patterns to the RegistrationController.java class. Added dynamic red and green color styling to indicate validation status, enhancing user feedback and experience.
> Added Real-Time Regex Validation with Visual Feedback for Text and Password Fields in RegistrationController.java - Nav Singh

- src/main/java/org/education/hospitalmanagementapp/controllers/BillingAndInvoiceController.java
- src/main/java/org/education/hospitalmanagementapp/services/AuthServiceClass.java
Fixed charging existing patients so that if a patient existed already in the database, the cost and service column for them will get updated rather than creating a new patient and record
> Fixed charging existing patients

- src/main/java/org/education/hospitalmanagementapp/controllers/RegistrationController.java
- src/main/java/org/education/hospitalmanagementapp/controllers/UserManagementController.java
Fixed RegistrationController.java and UserManagementController.java validation fields.
> Fixed RegistrationController.java and UserManagementController.java validation fields - Nav Singh

- src/main/java/org/education/hospitalmanagementapp/controllers/AppointmentSchedulerController.java
Implemented name field validation with regex for doctor and patient names. Add styling to indicate valid/invalid input in Appointment Scheduler.
> Added Name Field Validation and Styling for Appointment Scheduler - Nav Singh

- src/main/java/org/education/hospitalmanagementapp/controllers/RegistrationController.java
Added real-time validation for the confirm password field. Implemented the addConfirmPasswordValidation method to validate input dynamically. Updated the field to turn green when passwords match and red when they do not. Enhanced user experience with immediate feedback during registration.
> Added real-time validation for confirm password field - Nav Singh

- README.md
> Updated README.md - Nav Singh

- src/main/java/org/education/hospitalmanagementapp/controllers/BillingAndInvoiceController.java
- src/main/java/org/education/hospitalmanagementapp/controllers/PatientManagerController.java
- src/main/resources/org.education.hospitalmanagementapp/Billing_And_Invoices.fxml
Fixed clear buttons in PatientManagerController.java
> Fixed clear buttons in PatientManagerController.java

- src/main/java/org/education/hospitalmanagementapp/Patient.java
- src/main/java/org/education/hospitalmanagementapp/controllers/AppointmentSchedulerController.java
- src/main/java/org/education/hospitalmanagementapp/controllers/DashBoardController.java
- src/main/java/org/education/hospitalmanagementapp/controllers/ReportGeneratorController.java
- src/main/java/org/education/hospitalmanagementapp/services/Appointment.java
Added detailed JavaDoc comments to several classes for improved code documentation and readability. This update includes descriptions for class functionality, method parameters, return values, and other relevant details to enhance maintainability and understanding of the code.
> Added JavaDoc Comments to Multiple Classes - Nav Singh
